//ejercicios creacion de variable
//Una variable global de tipo var para mostrar el alcance global
var global = "Global";
//Variable local
let local = "Local";
//variable constante
const constante = "Constante";
let myDecimal= 10.45;
let Cadenadetexto = "Hola, mundo!";
let esVerdadero = true;
let esFalso = false;

console.log("variables: Global: " + global + "- Local: " + local + "- Constante:" + constante)
